version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          key: muscat-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: muscat-{{ checksum "pom.xml" }}

      - run: ./mvnw clean package

  test:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - run: ./mvnw verify

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          -build